general:
  out_dir: &out_dir checkpoints/imdb
  device: cpu
  num_epochs: 300
  target: &target movie
data:
  name: IMDB
  config:
    root: data/raw/imdb
model:
  name: HeteroNodeClassifier
  config:
    gnn_name: GAT
    gnn_config:
      in_channels: [-1, -1]
      hidden_channels: &hidden_channels 256
      num_layers: 2
      out_channels: *hidden_channels
      dropout: .5
      add_self_loops: False
    hidden_dim: *hidden_channels
    num_classes: &num_classes 3
    target_node_type: *target
    aggr: sum
optimizer:
  name: AdamW
  config:
    lr: 1e-3
criterion:
  name: CrossEntropyLoss
  config:
    weight: [3.76, 2.70, 2.74]
early_stop:
  name: EarlyStopping
  config:
    patience: 30
    verbose: True
    out_dir: *out_dir
scheduler:
  name: HFCosineScheduler
  config:
    num_warmup_steps: 30
metrics:
  accuracy:
    name: Accuracy
    config:
      task: &task multiclass
      average: macro
      num_classes: *num_classes
  f1:
    name: F1Score
    config:
      task: *task
      average: macro
      num_classes: *num_classes