dataset:
  data_class: Planetoid
  dataset_cfg:
    root: ./data/raw/planetoid
    name: Cora
export:
  output_dir: ./dataset_code/metrics/planetoid/1000
  num_nodes: 1000
  layout: spring
  scale: 1000
  use_tqdm: True
