dataset:
  data_class: OPFDataset
  dataset_cfg:
    root: ./data/raw/opd_dataset
    split: test
    topological_perturbations: True
export:
  output_dir: ./dataset_code/opd_dataset
  num_nodes: 50
  use_tqdm: True